#!/bin/bash
export MIRROR=${MIRROR:-http://fedorapeople.org/groups/katello}
export EPEL=${EPEL:-http://dl.fedoraproject.org/pub/epel}
export CANDLEPIN_REPO_BASEURL="$MIRROR/releases/yum/katello-candlepin"
export PULP_REPO_BASEURL="$MIRROR/releases/yum/katello-pulp"
export FOREMAN_REPO_BASEURL="$MIRROR/releases/yum/katello-foreman"
export KATELLO_REPO_BASEURL="$MIRROR/releases/yum/nightly"
export ADDITIONAL_PACKAGES="screen git mc"
export KATELLO_CONFIGURE_OPTIONS="-b --es-min-mem=64m --es-max-mem=64m"

PLAN=(
010-disable-iptables.sh
300-setup-repos-manual.sh
400-install-katello.sh
500-configure-katello.sh
999-updatedb.sh
)
